version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vendora_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vendora
      POSTGRES_USER: vendora_user
      POSTGRES_PASSWORD: vendora_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
